### PR TITLE
Fixed typo in modis_restservice_qc_filter_Python.ipynb

### PR DESCRIPTION
**Pull request by dlhvelasco**
Hi, thanks for the tutorial.

The comments at lines 348 and 351 are referring to `lstdata` yet the relevant code is actually for `qcdata`.
Vice-versa for the comments at lines 355 and 358. Fixed as this might be confusing.

Hope this helps.

### CODE REVIEW

**Review by jjmcnelis — APPROVED** [review]
Good eye! Thanks for the correction. Stay tuned for new MODIS and VIIRS content!

**Comment by dlhvelasco** [comment]
Looking forward to it!
By the way, I've got some inquiries about REST– may I email the ORNL DAAC Contact for this? Thanks.

**Comment by jjmcnelis** [comment]
Related to the MODIS and VIIRS API? I recommend you visit this page, if you haven't already:
https://modis.ornl.gov/data/modis_webservice.html
MODIS/VIIRS Web Service<https://modis.ornl.gov/data/modis_webservice.html>
The Web service provides users with subsets of MODIS/VIIRS Land Products through standards based RESTful (Representational State Transfer) Web service API.Through the API users can execute simple HTTP GET methods to retrieve MODIS/VIIRS Land Product subsets. Currently users can choose to receive the response content in csv or json formats.
modis.ornl.gov

Let me know if you have any problems.

Thanks again,
Jack

________________________________

**Comment by dlhvelasco** [comment]
Ah apologies for not being clear enough. Not quite on the implementation but yes, thank you for the link. 
Actually, would it be okay to email you my questions instead? I think I wouldn't want to extend this thread any longer 😅.
Thanks again.

**Comment by jjmcnelis** [comment]
Sure, no problem: mcnelisjj@ornl.gov
________________________________

**Comment by dlhvelasco** [comment]
I have just sent you an email. Thank you again!

**Pull request merged**
